name: pc-kernel
adopt-info: kernel
summary: |
    PC Kernel
description: PC Kernel
build-base: core22
type: kernel
grade: devel

parts:
  dracut-ubuntu-core:
    source-type: local
    source: .
    plugin: meson
    build-packages:
    - meson
    - pkg-config
    - dracut-core
    override-build: |
      snapcraftctl build
      cp -Tra "${SNAPCRAFT_PART_INSTALL}" /
    prime:
    - -*

  kernel:
    after:
    - dracut-ubuntu-core
    plugin: nil
    build-packages:
    - linux-image-generic
    - zstd
    - busybox
    - systemd
    - dracut-core
    - systemd-bootchart
    - snapd
    - sbsigntool
    override-pull: |
      snapcraftctl set-version $(dpkg-query --show --showformat='${Version}' linux-image-generic)
      snapcraftctl pull

    override-build: |
      kernelver="$(readlink /boot/vmlinuz | sed 's/^vmlinuz-//')"

      dracut                                                        \
        --conf /usr/local/share/dracut-ubuntu-core/dracut.conf      \
        kernel.efi-"${kernelver}" "${kernelver}"

      # FIXME: re-signing is not needed once the 2 next FIXMEs are
      # fixed
      sbattach --remove kernel.efi-"${kernelver}"

      # FIXME: get the systemd package to build with -Dsbat-distro
      if ! [ -r sbat.txt ]; then
        systemd_version="$(pkg-config --modversion systemd)"
        systemd_package_version="$(dpkg-query --show --showformat='${Version}' systemd)"
        cat <<EOF >sbat.txt
      sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
      systemd,1,The systemd Developers,systemd,${systemd_version},https://www.freedesktop.org/wiki/Software/systemd
      systemd.ubuntu,1,Ubuntu,systemd,${systemd_package_version},https://bugs.launchpad.net/ubuntu/
      EOF
      fi

      objcopy                                                       \
        --add-section .sbat=sbat.txt                                \
        --set-section-flags .sbat=contents,alloc,load,readonly,data \
        --change-section-vma .sbat=0x50000                          \
        --set-section-alignment .sbat=4096                          \
        kernel.efi-"${kernelver}"

      # FIXME: This is not needed from dracut 052
      objcopy --remove-section .cmdline kernel.efi-"${kernelver}"

      # FIXME: re-signing is not needed once the 2 previous FIXMEs are
      # fixed
      key="/usr/local/share/dracut-ubuntu-core/snakeoil/PkKek-1-snakeoil.key"
      cert="/usr/local/share/dracut-ubuntu-core/snakeoil/PkKek-1-snakeoil.pem"
      sbsign                       \
        --key "${key}"             \
        --cert "${cert}"           \
        --output "kernel.efi"      \
        kernel.efi-"${kernelver}"

      install -Dm700 kernel.efi "${SNAPCRAFT_PART_INSTALL}/kernel.efi"

      install -dm755 "${SNAPCRAFT_PART_INSTALL}/modules"
      cp -ra "/usr/lib/modules/${kernelver}" "${SNAPCRAFT_PART_INSTALL}/modules/"
      cp -ra "/usr/lib/firmware" "${SNAPCRAFT_PART_INSTALL}/"
